name: documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: mkdir public
      - run: npm i -g md-to-pdf
      - run: md-to-pdf --as-html --config-file ./config_html.json ./doc/ja.md
      - run: mv ./doc/ja.html ./public/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
  generate-pdf:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install ubuntu package
        run: |
          sudo apt-get update && sudo apt-get install calibre
          sudo apt-get install fonts-takao-mincho fonts-takao
      - uses: actions/checkout@v2
        with:
          ref: pdf
          path: ./pdf
      - run: npm i -g md-to-pdf
      - run: md-to-pdf --config-file ./config_pdf.json ./doc/ja.md
      - run: mv ./doc/ja.pdf ./pdf/doc/
      - name: commit files
        run: |
          cd ./pdf
          ls -la ./doc
          git status
          git branch
          git config --global user.email "17383696+kouya17@users.noreply.github.com"
          git config --global user.name "kouya17"
          git add ./doc/ja.pdf
          git commit -m "ci: generate pdf" -a
          git push origin pdf