name: documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: mkdir public
      - run: npm i -g md-to-pdf
      - run: md-to-pdf --as-html --config-file ./config_html.json ./doc/ja.md
      - run: mv ./doc/ja.html ./public/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public